# Azure Pipeline YAML file

name: 1.0$(Rev:.r)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

variables:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: bgfx
  _RELEASE_VERSION: v0
  _RELEASE_CONFIGURATION: Release
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)
  # BGFX defines ( multiple values can be set using ':','%' or 's' as a separator)
  BGFX_CONFIG: "DEBUG=1"

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: bx
    type: github
    endpoint: github_ci
    name: bkaradzic/bx
  - repository: bimg
    type: github
    endpoint: github_ci
    name: bkaradzic/bimg
  - repository: bgfx
    type: github
    endpoint: github_ci
    name: bkaradzic/bgfx

steps:
- checkout: self
- checkout: bx
- checkout: bimg
- checkout: bgfx
- task: PowerShell@2
  displayName: 'Generate GENie solution files'
  inputs:
    filePath: $(Build.Repository.LocalPath)\bgfxCI\.ci\prepare.ps1
  env:
    buildPath: $(Build.Repository.LocalPath)
- task: VSBuild@1
  displayName: 'Build $(_RELEASE_NAME)'
  inputs:
    solution: $(Build.Repository.LocalPath)\bgfx\.build\projects\vs2019\bgfx.sln
    platform: Win32
    configuration: $(_RELEASE_CONFIGURATION)
    msbuildArgs: /p:WindowsTargetPlatformVersion=10.0.19041.0
- task: PowerShell@2
  displayName: 'Package $(_RELEASE_NAME)'
  inputs:
    filePath: $(Build.Repository.LocalPath)\bgfxCI\.ci\package.ps1
  env:
    buildPath: $(Build.Repository.LocalPath)
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Delete $(_RELEASE_NAME) Release (Canary)'
  continueOnError: true
  inputs:
    gitHubConnection: github_ci
    action: delete
    tagSource: manual
    tag: canary
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Create $(_RELEASE_NAME) Release (Canary)'
  inputs:
    gitHubConnection: github_ci
    assets: $(Build.Repository.LocalPath)\.dist\*.zip
    isPreRelease: true
    tagSource: manual
    tag: canary
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
    releaseNotesSource: input
    releaseNotes: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Create $(_RELEASE_NAME) Release (Stable)'
  inputs:
    gitHubConnection: github_ci
    assets: $(Build.Repository.LocalPath)\.dist\*.zip
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
